services:
  #LARAVEL
  app:
    container_name: todolist-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    stdin_open: true
    tty: true

  #NGINX
  nginx:
    container_name: todolist-nginx
    image: nginx:alpine
    networks:
      - app-network
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d/
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /var/www/html
  
  #BANCO DE DADOS
  db:
    container_name: todolist-db
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: todolist
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    image: mysql:latest
    networks:
      - app-network
    ports:
      - 33306:3306
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - apptodolist:/var/lib/mysql

  #PHPMYADMIN
  db-manager:
    image: phpmyadmin
    container_name: todolist-db-manager
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=todolist
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=300M
    networks:
      - app-network

  #FRONTEND
  node-dev:
    container_name: todolist-node-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./frontend:/var/www/html
    working_dir: /var/www/html
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
volumes:
  apptodolist:
    driver: local
    name: apptodolist